[package]
name = "myso-rpc-loadgen"
version.workspace = true
edition = "2024"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
serde.workspace = true
tonic.workspace = true
futures.workspace = true
dirs.workspace = true
dashmap.workspace = true
itertools.workspace = true

shellexpand.workspace = true

myso-types.workspace = true
myso-keys.workspace = true
myso-sdk.workspace = true
telemetry-subscribers.workspace = true
myso-json-rpc-types.workspace = true
strum.workspace = true
shared-crypto.workspace = true
serde_json.workspace = true
strum_macros.workspace = true

[[bin]]
name = "myso-rpc-loadgen"
path = "src/main.rs"
