[package]
name = "myso-synthetic-ingestion"
version = "0.0.1"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
prost.workspace = true
simulacrum.workspace = true
myso-rpc.workspace = true
myso-test-transaction-builder.workspace = true
myso-types.workspace = true
telemetry-subscribers.workspace = true
tokio.workspace = true
tracing.workspace = true
zstd.workspace = true

[dev-dependencies]
tempfile.workspace = true
