[package]
name = "myso-telemetry"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
serde.workspace = true
reqwest.workspace = true
tracing.workspace = true

myso-core.workspace = true
