[package]
name = "LegacyRegulated"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySo = { local = "../../../../myso-framework/packages/myso-framework" }

[addresses]
legacy_regulated = "0x0"
