[package]
name = "myso-verifier-transactional-tests"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Transactional tests for MySo Verifier"
license = "Apache-2.0"
publish = false
edition = "2024"

[dev-dependencies]
datatest-stable.workspace = true
myso-transactional-test-runner.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]
