---
validator:
  hosts:
    validator:
      ansible_host: validator.example.com
      ansible_user: ubuntu
      myso_release: "$MYSO_SHA" # UPDATE THIS
      node_config: "./validator.yaml"
      genesis_blob: "./genesis.blob"
      keypair_path: "./key-pairs/"
