[package]
name = "myso-network"
version = "0.0.0"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
governor.workspace = true
serde.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
dashmap.workspace = true
tower.workspace = true
shared-crypto.workspace = true
eyre.workspace = true
http.workspace = true
tokio-rustls.workspace = true
tonic-health.workspace = true
tower-http.workspace = true
myso-http.workspace = true
myso-tls.workspace = true

myso-macros.workspace = true
myso-storage.workspace = true
myso-types.workspace = true
myso-config.workspace = true
myso-swarm-config.workspace = true
myso-simulator.workspace = true
myso-protocol-config.workspace = true
myso-data-ingestion-core.workspace = true

arc-swap.workspace = true
bcs.workspace = true
bytes.workspace = true
fastcrypto.workspace = true
fastcrypto-tbls.workspace = true
mysten-common.workspace = true
mysten-network.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true
tap.workspace = true
rand.workspace = true
anyhow.workspace = true
prometheus.workspace = true
mysten-metrics.workspace = true

[build-dependencies]
anemo-build.workspace = true
tonic-build.workspace = true

[dev-dependencies]
myso-macros.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["test-util"] }
ed25519-consensus.workspace = true
tempfile = "3.3.0"
