[package]
name = "myso-surfer"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
myso-core.workspace = true
myso-swarm-config.workspace = true
myso-json-rpc-types.workspace = true
myso-move-build.workspace = true
myso-protocol-config.workspace = true
myso-types.workspace = true
test-cluster.workspace = true
mysten-common.workspace = true

async-trait.workspace = true
bcs.workspace = true
clap.workspace = true
futures.workspace = true
indexmap.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tracing.workspace = true

move-binary-format.workspace = true
move-core-types.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
prometheus.workspace = true
myso-macros.workspace = true
myso-simulator.workspace = true

