[package]
name = "myso-indexer-alt-schema"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
diesel = {workspace = true, features = ["postgres_backend", "chrono"]}
diesel_migrations.workspace = true
serde.workspace = true
bcs.workspace = true
siphasher = "1.0"

move-core-types.workspace = true
myso-field-count.workspace = true
myso-protocol-config.workspace = true
myso-types.workspace = true
