[package]
name = "myso-name-service"
version.workspace = true
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
bcs.workspace = true
serde.workspace = true
thiserror.workspace = true

move-core-types.workspace = true

myso-types.workspace = true
