[package]
name = "myso-enum-compat-util"
version = "0.0.1"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
serde_yaml.workspace = true
