[package]
name = "myso-indexer-alt-restorer"
version = "0.1.0"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow = { version = "1.0.71", features = ["backtrace"] }
async-trait = "0.1.68"
clap = { version = "4.3.0", features = ["derive", "env"] }
futures = "0.3.28"
tracing = "0.1.37"
url.workspace = true

diesel = { workspace = true, features = ["chrono"] }
diesel-async = { workspace = true, features = ["bb8", "postgres", "async-connection-wrapper"] }
indicatif.workspace = true
object_store.workspace = true
prometheus.workspace = true
myso-config.workspace = true
myso-core.workspace = true
myso-data-ingestion-core.workspace = true
myso-field-count.workspace = true
myso-futures.workspace = true
myso-indexer-alt-schema.workspace = true
myso-pg-db.workspace = true
myso-snapshot.workspace = true
myso-storage.workspace = true
myso-types.workspace = true
tokio = { workspace = true, features = ["full"] }
telemetry-subscribers.workspace = true

[[bin]]
name = "myso-indexer-alt-restorer"
path = "src/main.rs"
