[package]
name = "myso-test-transaction-builder"
version = "0.0.1"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
bcs.workspace = true

shared-crypto.workspace = true
myso-genesis-builder.workspace = true
myso-move-build.workspace = true
myso-sdk.workspace = true
myso-rpc-api.workspace = true
myso-types.workspace = true

move-core-types.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(msim)',
] }
