[package]
name = "OrderBook"
version = "0.0.1"
published-at = "0xdee9"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
MySo = { local = "../myso-framework" }

[addresses]
orderbook = "0xdee9"
