[package]
name = "myso-protocol-config"
version = "0.1.0"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
serde.workspace = true
tracing.workspace = true
serde_with.workspace = true
myso-protocol-config-macros.workspace = true
schemars.workspace = true
clap.workspace = true
move-vm-config.workspace = true
serde-env.workspace = true
fastcrypto = { workspace = true }
move-core-types.workspace = true
move-binary-format.workspace = true
mysten-common.workspace = true

[dev-dependencies]
insta.workspace = true
