[package]
name = "BridgedUSDT"
version = "0.0.1"
edition = "legacy"

[dependencies]
MoveStdlib = { local = "../../../../crates/myso-framework/packages/move-stdlib" }
MySo = { local = "../../../../crates/myso-framework/packages/myso-framework" }

[addresses]
bridged_usdt = "0x0"
