[package]
name = "custom-indexer"
version = "0.0.1"
edition = "2024"

[dependencies]
async-trait = "0.1.83"
tokio = { version = "1.38.0", features = ["full"]}
myso_types = { git = "https://github.com/the-social-proof-foundation/myso-core.git", package = "myso-types", branch = "main" }
myso_data_ingestion_core = { git = "https://github.com/the-social-proof-foundation/myso-core.git", package = "myso-data-ingestion-core", branch = "main" }
prometheus = "0.13.3"
anyhow = "1.0.86"

[[bin]]
name = "local_reader"
path = "local_reader.rs"

[[bin]]
name = "remote_reader"
path = "remote_reader.rs"

[workspace]
