[package]
name = "myso-sdk"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

# This needs to be specified, in addition to the same setting
# in the workspace Cargo.toml.
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(msim)',
  'cfg(fail_points)',
] }

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
clap.workspace = true
colored.workspace = true
jsonrpsee.workspace = true
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
futures-core.workspace = true
futures.workspace = true
tokio.workspace = true
bcs.workspace = true
thiserror.workspace = true
reqwest.workspace = true

mysten-common.workspace = true
myso-json-rpc-api.workspace = true
myso-transaction-builder.workspace = true
myso-json-rpc-types.workspace = true
myso-types.workspace = true
myso-json.workspace = true
myso-keys.workspace = true
myso-config.workspace = true
shared-crypto.workspace = true
tracing.workspace = true
move-core-types.workspace = true
fastcrypto.workspace = true
myso-crypto.workspace = true
myso-rpc-api.workspace = true
myso-rpc.workspace = true
myso-sdk-types.workspace = true

# NOTE: It's important to keep the above dependency list short.
# This and the myso-json-rpc-api crate are widely used to develop on MySo and it's valuable
# to not have to pull in the entire myso repo for it.

[dev-dependencies]
clap.workspace = true
dirs.workspace = true
tempfile.workspace = true
futures-core.workspace = true
futures.workspace = true
rand.workspace = true
test-cluster.workspace = true
myso-macros.workspace = true
myso-simulator.workspace = true
prometheus.workspace = true
myso-protocol-config.workspace = true

[[example]]
name = "coin_read_api"
path = "examples/coin_read_api.rs"

[[example]]
name = "read_api"
path = "examples/read_api.rs"

[[example]]
name = "event_api"
path = "examples/event_api.rs"

[[example]]
name = "governance_api"
path = "examples/governance_api.rs"

[[example]]
name = "programmable_transactions_api"
path = "examples/programmable_transactions_api.rs"

[[example]]
name = "myso_client"
path = "examples/myso_client.rs"

[[example]]
name = "sign_tx_guide"
path = "examples/sign_tx_guide.rs"

[[example]]
name = "utils"
path = "examples/utils.rs"
crate-type = ["staticlib"]
