[package]
name = "myso-package-alt"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
bin-version.workspace = true
anyhow.workspace = true
clap.workspace = true
indexmap.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-package-alt.workspace = true
move-package-alt-compilation.workspace = true
serde.workspace = true
myso-package-management.workspace = true
shared-crypto.workspace = true
myso-config.workspace = true
myso-sdk.workspace = true
myso-json-rpc-types.workspace = true
myso-keys.workspace = true
tokio.workspace = true
tracing.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
