[package]
name = "myso-move-natives-latest"
version = "0.0.1"
edition = "2024"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
description = "Move framework for myso platform"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
better_any.workspace = true
bcs.workspace = true
indexmap.workspace = true
smallvec.workspace = true
rand = { workspace = true, features = ["small_rng"] }

fastcrypto-zkp.workspace = true
fastcrypto-vdf.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true

move-stdlib-natives = { path = "../../../external-crates/move/crates/move-stdlib-natives" }
move-vm-runtime = { path = "../../../external-crates/move/crates/move-vm-runtime" }
move-vm-types = { path = "../../../external-crates/move/crates/move-vm-types" }

myso-protocol-config.workspace = true
myso-types.workspace = true
tracing.workspace = true
