[package]
name = "myso-transaction-builder"
version = "0.0.1"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
futures.workspace = true
bcs.workspace = true

move-binary-format.workspace = true
myso-json-rpc-types.workspace = true
myso-types.workspace = true
myso-json.workspace = true
myso-protocol-config.workspace = true

move-core-types.workspace = true
