[package]
name = "service-boilerplate"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
anyhow.workspace = true
axum.workspace = true
mysten-service.workspace = true
prometheus.workspace = true
tracing.workspace = true
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }
