[package]
name = "myso-rpc-resolver"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
bcs.workspace = true
futures.workspace = true
lru.workspace = true
move-core-types.workspace = true
serde.workspace = true
serde_json.workspace = true
myso-package-resolver.workspace = true
myso-rpc-api.workspace = true
myso-types.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
