---
version: "3.9"
services:
  rosetta-online:
    image: mysten/myso-rosetta-devnet
    ports:
      - "9002:9002"
    expose:
      - "9002"
    working_dir: /myso/devnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/myso-rosetta generate-rosetta-cli-config --env devnet &
        /usr/local/bin/myso-rosetta start-online-remote-server --env devnet --genesis-path genesis.blob --full-node-url https://fullnode.devnet.mysocial.network:443
    stdin_open: true
    tty: true
  rosetta-offline:
    image: mysten/myso-rosetta-devnet
    ports:
      - "9003:9003"
    expose:
      - "9003"
    working_dir: /myso/devnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/myso-rosetta start-offline-server --env devnet
    stdin_open: true
    tty: true

