[package]
name = "bls_signature"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySo = { local = "../../../../crates/myso-framework/packages/myso-framework" }

[addresses]
bls_signature = "0x0"
