[package]
name = "myso-indexer-alt-social-schema"
version.workspace = true
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
chrono.workspace = true
diesel = { workspace = true, features = ["postgres_backend", "chrono", "serde_json", "64-column-tables"] }
diesel_migrations.workspace = true
serde.workspace = true
serde_json.workspace = true
