[package]
name = "myso-open-rpc"
version.workspace = true
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
bcs.workspace = true
versions.workspace = true

[dev-dependencies]
anyhow.workspace = true
fastcrypto.workspace = true
myso-json-rpc.workspace = true
myso-json-rpc-api.workspace = true
myso-json-rpc-types.workspace = true
myso-json.workspace = true
myso-types.workspace = true
myso-protocol-config.workspace = true
rand.workspace = true
insta.workspace = true
move-core-types.workspace = true
