---
version: "3.9"
services:
  myso-network:
    image: mysten/myso-rosetta-local
    ports:
      - "9000:9000"
    expose:
      - "9000"
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/myso start
  rosetta-online:
    image: mysten/myso-rosetta-local
    ports:
      - "9002:9002"
    expose:
      - "9002"
    working_dir: /myso/localnet
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/myso-rosetta generate-rosetta-cli-config &
        /usr/local/bin/myso-rosetta start-online-remote-server --full-node-url http://myso-network:9000
    stdin_open: true
    tty: true
  rosetta-offline:
    image: mysten/myso-rosetta-local
    ports:
      - "9003:9003"
    expose:
      - "9003"
    command:
      - /bin/bash
      - -c
      - |
        /usr/local/bin/myso-rosetta start-offline-server