[package]
name = "myso-tool"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
num_cpus.workspace = true
bcs.workspace = true
clap = { version = "4.1.4", features = ["derive"] }
colored.workspace = true
comfy-table.workspace = true
eyre.workspace = true
futures.workspace = true
hex.workspace = true
move-core-types.workspace = true
itertools.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
tracing.workspace = true
prometheus.workspace = true
object_store.workspace = true
indicatif.workspace = true
consensus-core.workspace = true
mysten-metrics.workspace = true

anemo-cli.workspace = true
anemo.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }
typed-store.workspace = true
fastcrypto.workspace = true

myso-config.workspace = true
myso-core.workspace = true
myso-data-ingestion-core.workspace = true
myso-network.workspace = true
myso-snapshot.workspace = true
myso-protocol-config.workspace = true
myso-replay.workspace = true
myso-rpc-api.workspace = true
myso-storage.workspace = true
myso-types.workspace = true
myso-package-dump.workspace = true
myso-tls.workspace = true
bin-version.workspace = true
