[package]
name = "myso-move"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
indoc.workspace = true
once_cell.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
tracing.workspace = true
prometheus.workspace = true
bin-version.workspace = true
serde.workspace = true
futures.workspace = true
toml.workspace = true

move-binary-format.workspace = true
move-cli.workspace = true
move-compiler.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
move-package-alt.workspace = true
move-package-alt-compilation.workspace = true
move-bytecode-source-map.workspace = true
move-unit-test.workspace = true
move-core-types.workspace = true
move-vm-config.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }

move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }
move-vm-types = { path = "../../external-crates/move/crates/move-vm-types" }
myso-move-natives = { path = "../../myso-execution/latest/myso-move-natives", package = "myso-move-natives-latest" }
myso-adapter = { path = "../../myso-execution/latest/myso-adapter", package = "myso-adapter-latest" }

myso-config.workspace = true
myso-move-build.workspace = true
myso-protocol-config.workspace = true
myso-sdk.workspace = true
myso-types.workspace = true
myso-package-alt.workspace = true
better_any = "0.1.1"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemalloc-ctl.workspace = true

[dev-dependencies]
futures.workspace = true
jsonrpsee.workspace = true
rand.workspace = true
tempfile.workspace = true
walkdir.workspace = true
insta.workspace = true

move-package-alt.workspace = true

mysten-metrics.workspace = true
myso-macros.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["tikv-jemalloc-ctl"]

[lints]
workspace = true

[features]
tracing = []
