# config.yaml format:

# URL of the remote store
# remote_store_url: <url>
# URL for Ethereum RPC
# eth_rpc_url: <url>
# Database connection URL
# db_url: <url>
# Path to the checkpoints
# checkpoints_path: <path>
# Number of concurrent operations
# concurrency: 1
# Bridge genesis checkpoint in MYSO, for testnet = 43917829
# bridge_genesis_checkpoint: <myso bridge genesis checkpoint>
# Ethereum to MySo bridge contract address
# eth_myso_bridge_contract_address: <contract_address>
# Starting block number
# start_block: <indexing_start_block>
# Client metric URL
# metric_url: <url>
# Client metric port
# metric_port: <port>
