[build]
builder = "dockerfile"
dockerfilePath = "crates/myso-bridge-indexer/Dockerfile"

[deploy]
startCommand = "bridge-indexer"
# healthcheckPath = "/"
# healthcheckTimeout = 60

[variables]
# Database Configuration
DATABASE_URL = "${{Postgres.DATABASE_URL}}"

# Optional: Logging configuration  
RUST_LOG = "info,myso_bridge_indexer=debug" 