[package]
name = "myso-security-watchdog"
version.workspace = true
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
arrow-array.workspace = true
mysten-metrics.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
chrono.workspace = true
snowflake-api.workspace = true
tokio-cron-scheduler = "0.10.0"
clap.workspace = true
prometheus.workspace = true
telemetry-subscribers.workspace = true
async-trait.workspace = true
uuid.workspace = true
lexical-util = "1.0.6"
reqwest = { workspace = true, features = ["json"] }
env_logger = "0.11.3"
