[package]
name = "slot_machine"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySo = { local = "../../../../crates/myso-framework/packages/myso-framework" }

[addresses]
slot_machine = "0x0"
