[package]
name = "myso-move-build"
version.workspace = true
edition = "2024"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
description = "Logic for building MySo Move Packages"
license = "Apache-2.0"
publish = false

[dependencies]
anyhow.workspace = true
fastcrypto.workspace = true
futures.workspace = true
thiserror.workspace = true
tempfile.workspace = true

move-bytecode-verifier = { path = "../../external-crates/move/crates/move-bytecode-verifier" }
myso-verifier = { path = "../../myso-execution/latest/myso-verifier", package = "myso-verifier-latest" }

serde-reflection.workspace = true
myso-types.workspace = true
myso-protocol-config.workspace = true
myso-package-alt.workspace = true
tokio.workspace = true
mysten-common.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-ir-types.workspace = true
move-package-alt.workspace = true
move-package-alt-compilation.workspace = true
move-symbol-pool.workspace = true

[dev-dependencies]
fs_extra.workspace = true
