[package]
name = "myso-json"
version = "0.0.0"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true

myso-types.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
fastcrypto.workspace = true

[dev-dependencies]
test-fuzz.workspace = true
myso-move-build.workspace = true
myso-framework.workspace = true
tokio.workspace = true
