[package]
name = "myso-storage"
version = "0.1.0"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
integer-encoding.workspace = true
async-trait.workspace = true
futures.workspace = true
num_enum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["full", "tracing"] }
tracing.workspace = true
byteorder.workspace = true
anyhow.workspace = true
tempfile.workspace = true
tap.workspace = true
reqwest.workspace = true
percent-encoding = "2.2.0"
chrono.workspace = true
object_store.workspace = true
backoff.workspace = true
bytes.workspace = true
parking_lot = { workspace = true, features = ["arc_lock"] }
bcs.workspace = true
prometheus.workspace = true
itertools.workspace = true
zstd.workspace = true
url.workspace = true
fastcrypto.workspace = true
clap = "4.3.2"
hyper.workspace = true
hyper-rustls.workspace = true
base64-url.workspace = true
telemetry-subscribers.workspace = true
indicatif.workspace = true
moka.workspace = true

myso-types.workspace = true
mysten-metrics.workspace = true
move-core-types.workspace = true
myso-json-rpc-types.workspace = true
myso-protocol-config.workspace = true
myso-config.workspace = true
typed-store.workspace = true
eyre.workspace = true
lru.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true

[dev-dependencies]
axum.workspace = true
anyhow.workspace = true
tempfile.workspace = true
once_cell.workspace = true
myso-test-transaction-builder.workspace = true
myso-simulator.workspace = true
myso-macros.workspace = true
