[package]
name = "myso-json-rpc-api"
version = "0.0.1"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
anyhow.workspace = true
jsonrpsee.workspace = true
once_cell.workspace = true
prometheus.workspace = true
tap.workspace = true
tracing.workspace = true
fastcrypto.workspace = true
mysten-metrics.workspace = true
myso-json.workspace = true
myso-json-rpc-types.workspace = true
myso-open-rpc.workspace = true
myso-open-rpc-macros.workspace = true
myso-types.workspace = true

# NOTE: It's important to keep the above dependency list short.
# This and the myso-sdk crate are widely used to develop on MySo and it's valuable
# to not have to pull in the entire myso repo for it.

[dev-dependencies]
