[package]
name = "mysten-common"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
version = "0.1.0"
edition = "2024"
publish = false

[lints]
workspace = true

[dependencies]
rand.workspace = true
antithesis_sdk.workspace = true
either.workspace = true
snap.workspace = true
once_cell.workspace = true
tokio.workspace = true
futures.workspace = true
parking_lot.workspace = true
reqwest.workspace = true
fastcrypto.workspace = true
mysten-metrics.workspace = true
myso-macros.workspace = true
tempfile.workspace = true
tracing.workspace = true
anyhow.workspace = true
serde_json.workspace = true
