[package]
name = "myso-macros"
version = "0.0.1"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]
myso-proc-macros.workspace = true
once_cell.workspace = true
futures.workspace = true
tracing.workspace = true
