[package]
name = "myso-oracle"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySo = { git = "https://github.com/the-social-proof-foundation/myso-core.git", subdir = "crates/myso-framework/packages/myso-framework", branch = "main" }

[addresses]
oracle = "0x0"
myso = "0x2"
