[package]
name = "owned_no_tto"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySo = { local = "../../../../crates/myso-framework/packages/myso-framework" }
common = { local = "../common" }

[addresses]
owned_no_tto = "0x0"
