[package]
name = "nft_rental"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySo = { local = "../../../crates/myso-framework/packages/myso-framework", override = true }
Kiosk = { git = "https://github.com/MystenLabs/apps.git", subdir = "kiosk", rev = "testnet" }

[addresses]
nft_rental = "0x0"
