[package]
name = "myso-json-rpc-tests"
version = "0.0.0"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lints]
workspace = true

[dependencies]

[dev-dependencies]
move-core-types.workspace = true
myso-config.workspace = true
myso-core.workspace = true
myso-keys.workspace = true
myso-move-build.workspace = true
myso-test-transaction-builder.workspace = true
myso-sdk.workspace = true
myso-macros.workspace = true
myso-simulator.workspace = true
myso-json.workspace = true
myso-json-rpc.workspace = true
myso-json-rpc-api.workspace = true
myso-json-rpc-types.workspace = true
myso-open-rpc.workspace = true
myso-open-rpc-macros.workspace = true
myso-protocol-config.workspace = true
myso-swarm-config.workspace = true
myso-types.workspace = true
test-cluster.workspace = true
telemetry-subscribers.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
hyper.workspace = true
jsonrpsee.workspace = true
prometheus.workspace = true
rand.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
shared-crypto.workspace = true
