[package]
name = "myso-field-count"
version.workspace = true
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
myso-field-count-derive.workspace = true
