[package]
name = "myso-move-natives-v2"
version = "0.1.0"
edition = "2021"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
description = "Move framework for myso platform"
license = "Apache-2.0"
publish = false

[dependencies]
better_any.workspace = true
bcs.workspace = true
indexmap.workspace = true
smallvec.workspace = true

fastcrypto-zkp.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true

move-stdlib-natives = { path = "../../../external-crates/move/move-execution/v2/crates/move-stdlib-natives", package = "move-stdlib-natives-v2" }
move-vm-runtime = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-runtime", package = "move-vm-runtime-v2" }
move-vm-types = { path = "../../../external-crates/move/move-execution/v2/crates/move-vm-types", package = "move-vm-types-v2" }

myso-protocol-config.workspace = true
myso-types.workspace = true
tracing.workspace = true
