[package]
name = "move-proc-macros"
version = "0.0.1"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn = { version = "2", features = ["full", "fold", "extra-traits"] }
enum-compat-util.workspace = true
