[package]
name = "myso-move-lsp"
version.workspace = true
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
bin-version.workspace = true
move-analyzer.workspace = true
move-compiler.workspace = true
myso-package-alt.workspace = true
myso-move-build.workspace = true
myso-package-management.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
tikv-jemalloc-ctl.workspace = true
tikv-jemallocator.workspace = true
