name: Trigger pre-build images for MySo commits

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
      - 'devnet'
      - 'testnet'
      - 'mainnet'
      - 'releases/myso-*-release'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  prebuild-myso-images:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Pre-build Images in MystenLabs/myso-operations
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # pin@v4.0.1
        with: 
          repository: MystenLabs/myso-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: prebuild-myso-images
          client-payload: >
            {
              "myso_commit": "${{ github.sha }}",
              "caller_name": "myso_repo_${{ github.ref_name }}",
              "push_to_dockerhub": "true",
              "build_arm64": "${{ github.ref_name != 'main' && (github.ref_name == 'devnet' || github.ref_name == 'testnet' || github.ref_name == 'mainnet' || (startsWith(github.ref_name, 'releases/myso-') && endsWith(github.ref_name, '-release'))) }}",
              "graphql_rpc": "true",
              "indexer_alt": "true",
              "stress": "true"
            }
