name: Trigger Release binaries builds

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'devnet'
      - 'testnet'
      - 'mainnet'
      - 'releases/myso-*-release'

concurrency: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  release-binaries:
    name: Trigger Release binaries builds
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Release binaries builds in MystenLabs/myso-operations
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # pin@v4.0.1
        with:
          repository: MystenLabs/myso-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: build-release-binaries
          client-payload: '{"myso_commit": "${{ github.sha }}"}'

  # Tag all myso images with branch name, so that they can be easily found
  tag-docker-hub-images:
    name: Tag myso docker images in DockerHub
    if: github.event_name == 'push' && contains(fromJSON('["devnet", "testnet", "mainnet"]'), github.ref_name)
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Tagging of images in DockerHub, in MystenLabs/myso-operations
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # pin@v4.0.1
        with:
          repository: MystenLabs/myso-operations
          token: ${{ secrets.DOCKER_BINARY_BUILDS_DISPATCH }}
          event-type: tag-docker-images
          client-payload: '{"myso_commit": "${{ github.sha }}", "tag": "${{ github.ref_name }}"}'
