[package]
name = "myso-indexer-alt"
version.workspace = true
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"

[[bin]]
name = "myso-indexer-alt"
path = "src/main.rs"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(msim)',
] }

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
chrono.workspace = true
bin-version.workspace = true
clap.workspace = true
const-str.workspace = true
dashmap.workspace = true
diesel = { workspace = true, features = ["chrono"] }
diesel-async = { workspace = true, features = ["bb8", "postgres", "async-connection-wrapper"] }
diesel_migrations.workspace = true
futures.workspace = true
hex.workspace = true
itertools.workspace = true
prometheus.workspace = true
serde.workspace = true
serde_json.workspace = true
telemetry-subscribers.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
url.workspace = true

move-core-types.workspace = true
myso-default-config.workspace = true
myso-indexer-alt-framework = { workspace = true, features = ["postgres"] }
myso-indexer-alt-metrics.workspace = true
myso-indexer-alt-schema.workspace = true
myso-protocol-config.workspace = true
myso-types.workspace = true
myso-synthetic-ingestion = { workspace = true, optional = true }

[dev-dependencies]
rand.workspace = true
tempfile.workspace = true
wiremock.workspace = true

[features]
default = []
benchmark = ["myso-synthetic-ingestion"]  # This will be used to enable benchmark mode
