[package]
name = "myso-kvstore"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
publish = false
edition = "2024"
version.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
async-trait.workspace = true
base64.workspace = true
bcs.workspace = true
clap.workspace = true
http.workspace = true
gcp_auth.workspace = true
humantime.workspace = true
prometheus.workspace = true
prost.workspace = true
prost-types.workspace = true
rustls.workspace = true
serde.workspace = true
myso-indexer-alt-framework.workspace = true
myso-indexer-alt-framework-store-traits.workspace = true
myso-indexer-alt-metrics.workspace = true
myso-types.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }
tonic = { workspace = true, features = ["transport"] }
tonic-prost.workspace = true
tracing.workspace = true

[dev-dependencies]
futures.workspace = true
myso-indexer-alt-framework = { workspace = true, features = ["cluster"] }
myso-keys.workspace = true
myso-rpc.workspace = true
test-cluster.workspace = true
tokio-stream.workspace = true
url.workspace = true
