[package]
name = "myso-metrics-push-client"
authors = ["Brandon Shaw <brandon@mysocial.network>"]
license = "Apache-2.0"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow.workspace = true
prometheus.workspace = true
reqwest.workspace = true
serde.workspace = true
snap.workspace = true
tokio.workspace = true
tracing.workspace = true

fastcrypto.workspace = true
mysten-metrics.workspace = true
myso-tls.workspace = true
myso-types.workspace = true
